#!/usr/bin/env python3
"""Generate release notes for claude-portable using the Claude API."""
import argparse
import json
import sys

import anthropic

MODEL = "claude-opus-4-7"

PROMPT_TEMPLATE = """\
You are writing release notes for **claude-portable v{version}**, a project that \
automatically repackages the official Anthropic Claude Code CLI \
(`@anthropic-ai/claude-code`) into portable archives that can be deployed on \
air-gapped or proxy-only servers without any installation.

Here is the npm package metadata for the upstream release:

```json
{npm_info}
```

Write concise, professional release notes in Markdown. Follow this structure exactly:

## Claude Code v{version} — Portable Release

[One sentence: this is the portable packaging of Claude Code v{version}, noting \
the 8 supported platforms.]

### Supported Platforms

| Platform | Archive | Notes |
|----------|---------|-------|
| Linux x86-64 (glibc) | `.tar.gz` | Ubuntu 20.04+, Debian 10+, CentOS 7+ |
| Linux ARM64 (glibc) | `.tar.gz` | Ubuntu 20.04 ARM+ |
| Linux x86-64 (musl) | `.tar.gz` | Alpine 3.19+ |
| Linux ARM64 (musl) | `.tar.gz` | Alpine ARM |
| macOS Apple Silicon | `.tar.gz` | macOS 13+, M1/M2/M3 |
| macOS Intel | `.tar.gz` | macOS 13+, Intel |
| Windows x86-64 | `.zip` | Windows 10+ |
| Windows ARM64 | `.zip` | Windows 11 ARM |

### Quick Start

```bash
# Linux x86-64 example
tar xzf claude-portable-linux-x64-v{version}.tar.gz
export ANTHROPIC_API_KEY=sk-ant-...
export HTTPS_PROXY=http://your-proxy:8080   # if behind a proxy
./claude-portable-linux-x64-v{version}/claude --version
```

### Notes

[2–4 bullet points. Be factual. Mention: DISABLE_AUTOUPDATER is set by the \
launcher; no Node.js or package manager needed at runtime; proxy env vars \
(HTTPS_PROXY, HTTP_PROXY, NODE_EXTRA_CA_CERTS) are supported; ANTHROPIC_API_KEY \
must be set by the user.]

Keep the entire response under 400 words. Do not add any preamble or closing remarks.\
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--npm-info", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    with open(args.npm_info) as f:
        raw = json.load(f)

    # Trim to avoid huge prompts
    slim = {k: raw.get(k) for k in ("name", "version", "description", "keywords", "homepage")}
    npm_info_str = json.dumps(slim, indent=2)

    client = anthropic.Anthropic()
    prompt = PROMPT_TEMPLATE.format(version=args.version, npm_info=npm_info_str)

    print(f"Generating release notes with {MODEL} ...")
    message = client.messages.create(
        model=MODEL,
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )

    content = message.content[0].text.strip()
    footer = f"\n\n---\n*Generated by [Claude Code](https://claude.ai/code) ({MODEL})*"
    output = content + footer

    with open(args.output, "w") as f:
        f.write(output)

    print(f"Written to {args.output}")
    print("--- preview ---")
    print(output[:600])
    print("...")


if __name__ == "__main__":
    main()
