#!/usr/bin/env python3
"""Local helper: generate release notes by running the claude CLI.

In CI this logic lives directly in watch-upstream-release.yml.
Use this script for local testing:

  ANTHROPIC_API_KEY=sk-ant-... python3 scripts/generate-release-notes.py \\
      --version 2.1.116 --output /tmp/notes.md
"""
import argparse
import subprocess
import sys
import shutil
import textwrap

MODEL = "claude-opus-4-7"


def build_prompt(version: str) -> str:
    return textwrap.dedent(f"""\
        Write release notes for **claude-portable v{version}**.

        claude-portable automatically repackages the official Anthropic Claude Code CLI
        (@anthropic-ai/claude-code) into portable, self-contained archives for
        air-gapped or proxy-only servers that cannot run package managers or connect
        to npm at deploy time.

        Step 1 — Use WebFetch to read the upstream Claude Code release notes at:
        https://github.com/anthropics/claude-code/releases/tag/v{version}

        Step 2 — Write the following Markdown document:

        ### Claude Code v{version} — Portable Release

        [One sentence: portable packaging of Claude Code v{version} for 8 platforms,
        designed for air-gapped / proxy-only deployment.]

        ### What's New in Claude Code v{version}

        [Summarize the key changes you read from the upstream release page. Be specific —
        name the features, commands, and bug fixes. Group into 3–5 bullet points.
        Do NOT copy verbatim; distill the highlights.]

        ### Supported Platforms

        | Platform | Archive | Notes |
        |----------|---------|-------|
        | Linux x86-64 (glibc) | .tar.gz | Ubuntu 20.04+, Debian 10+, CentOS 7+ |
        | Linux ARM64 (glibc) | .tar.gz | Ubuntu 20.04 ARM+ |
        | Linux x86-64 (musl) | .tar.gz | Alpine 3.19+ |
        | Linux ARM64 (musl) | .tar.gz | Alpine ARM |
        | macOS Apple Silicon | .tar.gz | macOS 13+, M1/M2/M3 |
        | macOS Intel | .tar.gz | macOS 13+, Intel |
        | Windows x86-64 | .zip | Windows 10+ |
        | Windows ARM64 | .zip | Windows 11 ARM |

        ### Quick Start

        ```bash
        tar xzf claude-portable-linux-x64-v{version}.tar.gz
        export ANTHROPIC_API_KEY=sk-ant-...
        export HTTPS_PROXY=http://your-proxy:8080   # if behind a proxy
        ./claude-portable-linux-x64-v{version}/claude --version
        ```

        ### Portable Packaging Notes

        - The launcher script injects `DISABLE_AUTOUPDATER=1` automatically — the binary never attempts self-update.
        - No Node.js, npm, or any package manager is needed on the target machine at runtime.
        - Standard proxy environment variables (`HTTPS_PROXY`, `HTTP_PROXY`, `NO_PROXY`, `NODE_EXTRA_CA_CERTS`) are forwarded transparently.

        Keep the entire document under 550 words. Output ONLY the Markdown release notes.
        Do NOT include any meta-commentary, notes about the generation process, observations
        about tool output, or warnings. The output is used verbatim as a GitHub release body.
    """)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    claude_bin = shutil.which("claude")
    if not claude_bin:
        print("ERROR: 'claude' not found in PATH. Install with: npm install -g @anthropic-ai/claude-code",
              file=sys.stderr)
        sys.exit(1)

    prompt = build_prompt(args.version)

    print(f"Running claude --model {MODEL} --allowedTools WebFetch ...")
    result = subprocess.run(
        [claude_bin, "--model", MODEL, "--allowedTools", "WebFetch",
         "--output-format", "text", "-p", prompt],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        print(f"ERROR: claude exited with {result.returncode}", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    content = result.stdout.strip()
    footer = f"\n\n---\n*Generated by [Claude Code](https://claude.ai/code) ({MODEL})*"
    output = content + footer

    with open(args.output, "w") as f:
        f.write(output)

    print(f"Written to {args.output}")
    print("--- preview (first 600 chars) ---")
    print(output[:600])


if __name__ == "__main__":
    main()
